export function QrSvg({ className = "", ...props }) {
  return (
    <svg
    fill="currentColor"
    stroke="currentColor"
    strokeWidth="0"
    viewBox="0 0 512 512"
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      {...props}
  >
    <rect
      className="svgC"
      width="80"
      height="80"
      x="336"
      y="336"
      stroke="none"
      rx="8"
      ry="8"
    />
    <rect
      width="64"
      height="64"
      x="272"
      y="272"
      stroke="none"
      rx="8"
      ry="8"
    />
    <rect
      width="64"
      height="64"
      x="416"
      y="416"
      stroke="none"
      rx="8"
      ry="8"
    />
    <rect
      width="48"
      height="48"
      x="432"
      y="272"
      stroke="none"
      rx="8"
      ry="8"
    />
    <rect
      width="48"
      height="48"
      x="272"
      y="432"
      stroke="none"
      rx="8"
      ry="8"
    />
    <rect
      width="80"
      height="80"
      x="336"
      y="96"
      stroke="none"
      rx="8"
      ry="8"
      className="svgC"
    />
    <rect
      width="176"
      height="176"
      x="288"
      y="48"
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth="32"
      rx="16"
      ry="16"
    />
    <rect
      width="80"
      height="80"
      x="96"
      y="96"
      stroke="none"
      rx="8"
      ry="8"
      className="svgC"
    />
    <rect
      width="176"
      height="176"
      x="48"
      y="48"
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth="32"
      rx="16"
      ry="16"
    />
    <rect
      width="80"
      height="80"
      x="96"
      y="336"
      stroke="none"
      rx="8"
      ry="8"
      className="svgC"
    />
    <rect
      width="176"
      height="176"
      x="48"
      y="288"
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth="32"
      rx="16"
      ry="16"
    />
  </svg>
  );
}
